# Generated by Django 4.1.7 on 2023-04-20 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequirementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('priority', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('version', models.CharField(max_length=100)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.requirementtype')),
            ],
        ),
    ]
